# The config file for running C.elegans 
# Has all the paramaters needed to run a full pipeline

run_name: testRunA
output_dir: "test/20221020_Celegans/output"
fasta: "data/transcriptomes/Celegans.cdna.all.fa.gz"
idx_name: "Celegans"
fastq_R1: [
    "data/fastq/SRR21711053.fastq.gz",
    "data/fastq/SRR21711057.fastq.gz",
    "data/fastq/SRR21711073.fastq.gz",
    "data/fastq/SRR21711077.fastq.gz"
    ]
fastq_R2 : 
threads: 1
single_cell: False 
